name = "mehanik-poltava"
main = "worker.js"
compatibility_date = "2026-08-17"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "mehanik-db"
database_id = "2b6cab29-e36a-4357-88a4-2605a9e87fbc"
migrations_dir = "migrations"
